# Generated by Django 3.1.3 on 2020-11-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgmeta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
