# Generated by Django 3.1.3 on 2020-11-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgmeta', '0002_imageset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='name',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
