# Generated by Django 3.1.3 on 2020-11-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgmeta', '0003_auto_20201108_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageset',
            name='name',
        ),
        migrations.AlterField(
            model_name='imageset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
